### ISSUE TITLE
unable to compile in ubuntu 16.04 LTS with compiler gcc version 5.4.0 20160609

### ISSUE THREAD

**Issue by abilashjram** [martinhaefner/qnxcomm#1]
I am getting the following error when I try to compile this module

/xxx/Public/qnxcomm/kernel/internal_msgsend.c:46:17: error: implicit declaration of function ‘memcpy_fromiovec’ [-Werror=implicit-function-declaration]
    if (unlikely(memcpy_fromiovec(inbuf, _iov->in, inlen)))

Am I missing any linux specific headers?
